export const root =  '/';
export const organization = '/org';
export const people = '/people';
export const search =  '/search/org';
export const peopleSearch = '/search/people';
export const organizationProfile =  '/org/:ein';
export const copyrightPolicy =  '/dmca-copyright-policy';
export const privacyPolicy =  '/privacy-policy';
export const termsOfService = '/terms-of-service';
export const contact = '/contact';
export const benchmark = '/benchmark';
export const pro = '/pro';  // redirects to /customdata
export const resources = '/resources';
export const api = '/api';
export const productCatalog = '/catalog';
export const data = '/data';  // redirects to /resources
export const notFound = '/not-found';
export const customData = '/customdata';
export const exampleSearch = '/org/135562162/helen-keller-international-incorporated';
export const searchData = '/search/data'

export const mail = 'mailto:inquiries@open990.com';
export const davidMail = 'mailto:david@990consulting.com';
export const heatherMail = 'mailto:heather@990consulting.com';
export const inquiriesMail = 'mailto:inquiries@990consulting.com';
